# start window/pane index at 1
set -g base-index 1
set -g pane-base-index 1

# re-number windows when one is closed
set -g renumber-windows on

# re-mapping prefix
unbind-key C-b
set-option -g prefix C-Space    # setting prefix from C-b to C-Space
bind-key C-Space send-prefix    # send C-Space to other apps or the shell

# split panel
unbind %
unbind '"'
bind '\' split-window -h -c '#{pane_current_path}'
bind '-' split-window -v -c '#{pane_current_path}'

# use Alt-arrows without prefix to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# use Shift-arrows to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window

# Improve term colors
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Tokynight Theme - undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# increase scrollback buffer to 10000
set -g history-limit 10000

# activity notifications
setw -g monitor-activity on
setw -g visual-activity on

# escape time setting based on nvim healthcheck
set -g escape-time 10

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

# dracula plugin options - status bar theme
set -g @dracula-plugins "battery cpu-usage time"
set -g @dracula-show-left-icon session
set -g @dracula-military-time true

# Initialize TMUX plugin manager 
run '~/.tmux/plugins/tpm/tpm'
